### ISSUE TITLE
Bug: Path mapping between a Windows scene and a Linux worker does not work as expected

### ISSUE THREAD

**Issue by Ahuge** [aws-deadline/deadline-cloud-for-cinema-4d#118]
### Describe the bug

The `c4d.RDATA_PATH` (output path) appear as a relative path on Linux when it is actually a Windows path.

For example:

*On Windows*: `P:\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png`
*On Linux*: `./P:/ahughes/_DeadlineCloudExamples/simple_c4d_naming_output/image.png`

The Linux path appears to be relative and therefore the `map_path` call returns a relative Linux path and the entire folder structure gets recreated relative to the scene file.

This causes additional issues because certain characters cannot be represented on Windows filesystems in paths (For example, the above path that the image.png gets written out to will be as follows `P:\ahughes\_DeadlineCloudExamples\P_\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png` because Windows turns the `P:` into `P_`)

### Expected Behaviour

I would expect Cinema4D to give us a non-relative path, but I guess we have to have the adaptor work around this and detect that the path is a relative Windows path and treat it as absolute?

### Current Behaviour

A relative path is returned and converted to Linux, so the entire filesystem is recreated from the scene_file
`P:\ahughes\_DeadlineCloudExamples\P_\ahughes\_DeadlineCloudExamples\simple_c4d_naming_output\image.png` 

### Reproduction Steps

Create a scene in Windows Cinema4D and set the output path to be some absolute Windows path (I believe it converts it to absolute regardless) and then render the scene on a Linux Commandline worker.

Here is my modified plugin that you can use to just test the pathing:
```python
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
import os
import sys
import traceback

print('c4d python version: %s' % sys.version)
print('system paths:')
for n in sys.path:
    print(n)

import c4d

def setTake(take_name):
    doc = c4d.documents.GetActiveDocument()
    take_data = doc.GetTakeData()
    if not take_data:
        return

    def get_child_takes(take):
        child_takes = take.GetChildren()
        all_takes = child_takes
        if child_takes:
            for child_take in child_takes:
                all_takes.extend(get_child_takes(child_take))
        return all_takes

    main_take = take_data.GetCurrentTake()
    all_takes = [main_take] + get_child_takes(main_take)

    take = None
    for take in all_takes:
        if take.GetName() == take_name:
            break
    if take is None:
        print("Error: take not found: %s" % take_name)
    take_data.SetCurrentTake(take)


def parse_argv(argv):
    for arg in argv:
        if arg.find("-RdataTest") == 0:
            import c4d
            scene_file = "<PathToYourSceneFile>"
            print("Loading: {}".format(scene_file))
            doc = c4d.documents.LoadDocument(
                scene_file, c4d.SCENEFILTER_OBJECTS | c4d.SCENEFILTER_MATERIALS
            )
            c4d.documents.InsertBaseDocument(doc)
            c4d.documents.SetActiveDocument(doc)

            setTake("Main")

            doc = c4d.documents.GetActiveDocument()
            render_data = doc.GetActiveRenderData()
            print("RDATA_PATH: %s" % (render_data[c4d.RDATA_PATH]))
            return True
    return False


def PluginMessage(id, data):
    if id == c4d.C4DPL_COMMANDLINEARGS:
        return parse_argv(sys.argv)
    return False
```

### Environment

At minimum:
1. Operating system: Scene file created on Windows, Worker running RockyLinux9
2. Version of Cinema 4D: Cinema4D R26 on Windows Cinema4D 2024 on Linux
3: Version of this package: 0.5.4

Please share other details about your environment that you think might be relevant to reproducing the bug.

**Comment by Ahuge** [comment]
[simple_c4d_texture_linux_naming.c4d.zip](https://github.com/user-attachments/files/17962902/simple_c4d_texture_linux_naming.c4d.zip)

Attached is my simple scenefile but it should be easy to reproduce

**Comment by joel-wong-aws** [comment]
Thank you @Ahuge for the GitHub issue! We really appreciate the detailed reproduction steps and the sample scene. I've added this ticket to our backlog to investigate.

**Comment by joel-wong-aws** [comment]
I've been investigating this issue this week and have reproduced it. I'll dig into the root cause!
