### ISSUE TITLE
Bug: Adaptor doesn't recognize "CRITICAL stop" error

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-cinema-4d#51]
### Expected Behaviour

I expect the job status in the DCM to accurately reflect when a render has failed.

### Current Behaviour

I just ran a job where the logs reported a "CRITICAL stop" error, but the DCM marked the job as a success. The fix would probably just require adjusting the way we parse the log output of C4D.

I've attached a log of the job.
[Deadline Cloud Farm_Customer Managed Jobs_session-7faa4fd9cf2a4dfeabd65ee9a1c2ac25.log](https://github.com/user-attachments/files/15973717/Deadline.Cloud.Farm_Customer.Managed.Jobs_session-7faa4fd9cf2a4dfeabd65ee9a1c2ac25.log)

### Reproduction Steps

I am not sure how to reproduce the issue, but I experience this issue on every C4D render in my farm.

### Code Snippet

n/a

**Comment by yuanmich2** [comment]
To add some context, this error pops up when the user running the render doesn't have access to the output directory.

The PR to fix this issue would just append a regex that matches the error logs I attached to these few lines in the adaptor: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/9e00966d9e55fa081505c6cf3c326090f935400d/src/deadline/cinema4d_adaptor/Cinema4DAdaptor/adaptor.py#L192C1-L194C87

**Comment by karthikbekalp** [comment]
This issue should have been fixed by https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/pull/72
