### ISSUE TITLE
Feature request: Submitter should force a scene save before submission

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-cinema-4d#53]
### Use Case

I often forget to save changes to my scene before hitting the submit button and would like the submitter to force me to save before the render job goes out.

I've attached a log of one example where I had never saved a scene so the job attachments failed to upload anything which resulted in a "scene does not exist" error.

[Deadline Cloud Farm_Customer Managed Jobs_session-027787349ca84e769f62f8a6e6b24acb.log](https://github.com/user-attachments/files/15974129/Deadline.Cloud.Farm_Customer.Managed.Jobs_session-027787349ca84e769f62f8a6e6b24acb.log)

### Proposed Solution

The submitter should be able to check if there are any unsaved changes and prompt the user to save before submission. This was the default behavior in Deadline 10.

**Comment by karthikbekalp** [comment]
Closing this issue as we have merged a fix for it. https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/pull/69
