### ISSUE TITLE
Bug: Adaptor is not pathmapping the output path.

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-cinema-4d#55]
### Expected Behaviour

When using job attachments or when specifying a custom output path, the adaptor should overwrite any settings saved in the scene file. When using job attachments, the output path should be somewhere in the assetroot directory in the openjd session folder. When a custom output path and storage profile are used, the custom output path should be used.

### Current Behaviour

The render will always export to the path defined in the render settings.

### Reproduction Steps

Create a new scene. Define an output path that is accessible by your render job user in your render settings. Save your scene.

Bring up the submitter and change the output directory or submit to a queue that uses job attachments.

After the render completes, DCM will report no output files to download and your output will appear in the original output directory defined in the render settings.

### Code Snippet

n/a

**Comment by yuanmich2** [comment]
It looks like the adaptor isn't setting the path at all.

These couple of lines set the frame range of the render by editing the render data: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/9f3813c65451f073cea4d256817dd2f927b906c0/src/deadline/cinema4d_adaptor/Cinema4DClient/cinema4d_handler.py#L42C1-L44C50

To edit the path, you'd just edit the RDATA_PATH key in the render data. Docs on RDATA_PATH here: https://developers.maxon.net/docs/py/2024_2_0/modules/c4d.documents/RenderData/index.html#c4d.documents.RenderData

**Comment by yuanmich2** [comment]
Confirmed that adding a line like
`self.render_data[c4d.RDATA_PATH] = "C:/some/random/path/output_filename"`
Added to the section I linked in my last message successfully redirects the output. I'd make a PR, but I don't know how to extract the pathmapped output directory from the openjd description.

**Comment by epmog** [comment]
This is partially resolved by https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/pull/57

However, that's a quick fix to get the existing output paths in the scene path mapped. The longer term solution is for us to pass along the output directory and multipass directory through to the adaptor such that users can override the path from the submitter without being forced to save it in the scene file.

**Comment by epmog** [comment]
To do the actual fix, we'll need to: 
1. Add the options to the submitter. Not sure how we want to present the multipass path. Optional checkbox to enable to match how C4D does it?
    * load from scene: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_submitter/cinema4d_render_submitter.py#L247
    * add to UI: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_submitter/ui/components/scene_settings_tab.py#L99-L100
2. Add job parameters for output path and multipass output:
     * https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_submitter/adaptor_cinema4d_job_template.yaml#L20-L27
3. Add output and multipass output to the adaptor interface
    * schema: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_adaptor/Cinema4DAdaptor/schemas/init_data.schema.json
    * first actions: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_adaptor/Cinema4DAdaptor/adaptor.py#L29
    * create functions to set the output/multipass output and add to action dict: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_adaptor/Cinema4DClient/cinema4d_handler.py#L27-L32
3. Add job parameters to the init_data.yml
    * https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/mainline/src/deadline/cinema4d_submitter/adaptor_cinema4d_job_template.yaml#L40-L45

**Comment by karthikbekalp** [comment]
Resolving this issue as the PR with the fix has been merged!
