### ISSUE TITLE
Feature request: Mac Submitter Installers

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-cinema-4d#61]
### Use Case

There's no obvious instructions on how to manually install the submitters and the instructions on the Development.md page only sets environment variables within the terminal session on Mac.

### Proposed Solution

Improved instructions or a simple installer script for Mac users.

**Comment by karthikbekalp** [comment]
Closing the issue now that the documentation is updated for Mac
